apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-config
  namespace: delivery
  labels:
    app: notification-service
data:
  POSTGRES_DB: notification_db
  SPRING_DATASOURCE_URL: jdbc:postgresql://notification-db:5432/notification_db
