spring.application.name=tracking-service

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update


management.endpoints.web.exposure.include=health,info,circuitbreakers,circuitbreakerevents,retries,retryevents
management.endpoint.health.probes.enabled=true
management.endpoint.health.group.readiness.include=readinessState,db

shipment.client.base-url=${SHIPMENT_SERVICE_URL:http://localhost:8082}

# Circuit Breaker
resilience4j.circuitbreaker.instances.shipmentClient.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.shipmentClient.sliding-window-size=10
resilience4j.circuitbreaker.instances.shipmentClient.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.shipmentClient.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.shipmentClient.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.shipmentClient.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.shipmentClient.automatic-transition-from-open-to-half-open-enabled=true

# Retry
resilience4j.retry.instances.shipmentClient.max-attempts=3
resilience4j.retry.instances.shipmentClient.wait-duration=500ms
resilience4j.retry.instances.shipmentClient.enable-exponential-backoff=true
resilience4j.retry.instances.shipmentClient.exponential-backoff-multiplier=2
#jitter
resilience4j.retry.instances.shipmentClient.enable-randomized-wait=true
resilience4j.retry.instances.shipmentClient.randomized-wait-factor=0.5

# Semaphore Bulkhead
resilience4j.bulkhead.instances.shipmentClient.max-concurrent-calls=20